"""
Listado de medios de prensa que el ingester recoge por RSS.

Verificado en vivo (HTTP 200 + XML RSS válido). Cargado por
`pipeline.seed_fuentes` en `prensa.fuentes` con UPSERT por slug.
"""

from __future__ import annotations

from typing import TypedDict


class Fuente(TypedDict):
    slug: str
    nombre: str
    rss_url: str
    web_url: str
    idioma: str
    pais: str
    color: str
    sesgo: str


FUENTES: list[Fuente] = [
    # === izquierda / centro_izq ===
    {
        "slug": "el-pais",
        "nombre": "El País",
        "rss_url": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
        "web_url": "https://elpais.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#a82c2c",
        "sesgo": "centro_izq",
    },
    {
        "slug": "eldiario-es",
        "nombre": "elDiario.es",
        "rss_url": "https://www.eldiario.es/rss/",
        "web_url": "https://www.eldiario.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#e63946",
        "sesgo": "izquierda",
    },
    {
        "slug": "infolibre",
        "nombre": "InfoLibre",
        "rss_url": "https://www.infolibre.es/rss/",
        "web_url": "https://www.infolibre.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#d62828",
        "sesgo": "izquierda",
    },
    {
        "slug": "la-marea",
        "nombre": "La Marea",
        "rss_url": "https://www.lamarea.com/feed/",
        "web_url": "https://www.lamarea.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#0a8754",
        "sesgo": "izquierda",
    },
    {
        "slug": "huffpost-es",
        "nombre": "HuffPost España",
        "rss_url": "https://www.huffingtonpost.es/feeds/index.xml",
        "web_url": "https://www.huffingtonpost.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#0dbe98",
        "sesgo": "centro_izq",
    },

    # === centro ===
    {
        "slug": "el-confidencial",
        "nombre": "El Confidencial",
        "rss_url": "https://rss.elconfidencial.com/espana/",
        "web_url": "https://www.elconfidencial.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#c8102e",
        "sesgo": "centro",
    },
    {
        "slug": "el-periodico",
        "nombre": "El Periódico",
        "rss_url": "https://www.elperiodico.com/es/rss/rss_portada.xml",
        "web_url": "https://www.elperiodico.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#e30613",
        "sesgo": "centro_izq",
    },
    {
        "slug": "el-independiente",
        "nombre": "El Independiente",
        "rss_url": "https://www.elindependiente.com/feed/",
        "web_url": "https://www.elindependiente.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#1f3864",
        "sesgo": "centro",
    },
    {
        "slug": "heraldo",
        "nombre": "Heraldo de Aragón",
        "rss_url": "https://www.heraldo.es/rss/",
        "web_url": "https://www.heraldo.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#0e4c92",
        "sesgo": "centro",
    },
    {
        "slug": "newtral",
        "nombre": "Newtral",
        "rss_url": "https://www.newtral.es/feed/",
        "web_url": "https://www.newtral.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#21c685",
        "sesgo": "centro",
    },

    # === centro_der / derecha ===
    {
        "slug": "el-mundo",
        "nombre": "El Mundo",
        "rss_url": "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
        "web_url": "https://www.elmundo.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#cc0000",
        "sesgo": "centro_der",
    },
    {
        "slug": "abc",
        "nombre": "ABC",
        "rss_url": "https://www.abc.es/rss/feeds/abc_ultima.xml",
        "web_url": "https://www.abc.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#e2231a",
        "sesgo": "derecha",
    },
    {
        "slug": "el-espanol",
        "nombre": "El Español",
        "rss_url": "https://www.elespanol.com/rss/",
        "web_url": "https://www.elespanol.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#f4a300",
        "sesgo": "centro_der",
    },
    {
        "slug": "okdiario",
        "nombre": "OK Diario",
        "rss_url": "https://okdiario.com/feed",
        "web_url": "https://okdiario.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#005baa",
        "sesgo": "derecha",
    },
    {
        "slug": "libertad-digital",
        "nombre": "Libertad Digital",
        "rss_url": "https://feeds2.feedburner.com/libertaddigital/portada",
        "web_url": "https://www.libertaddigital.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#0d3b66",
        "sesgo": "derecha",
    },

    # === generalistas / agencias ===
    {
        "slug": "20minutos",
        "nombre": "20 Minutos",
        "rss_url": "https://www.20minutos.es/rss",
        "web_url": "https://www.20minutos.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#e30613",
        "sesgo": "centro",
    },
    {
        "slug": "europa-press",
        "nombre": "Europa Press",
        "rss_url": "https://www.europapress.es/rss/rss.aspx",
        "web_url": "https://www.europapress.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#003c79",
        "sesgo": "centro",
    },
    {
        "slug": "cope",
        "nombre": "COPE",
        "rss_url": "https://www.cope.es/api/es/news/rss.xml",
        "web_url": "https://www.cope.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#0c2340",
        "sesgo": "centro_der",
    },

    # === agencia / tv / radio ===
    {
        "slug": "rtve-noticias",
        "nombre": "RTVE Noticias",
        "rss_url": "https://www.rtve.es/rss/temas_noticias.xml",
        "web_url": "https://www.rtve.es/noticias",
        "idioma": "es",
        "pais": "ES",
        "color": "#0099ff",
        "sesgo": "centro",
    },

    # === adicionales nacional / opinion / analisis ===
    {
        "slug": "the-objective",
        "nombre": "The Objective",
        "rss_url": "https://theobjective.com/feed/",
        "web_url": "https://theobjective.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#111111",
        "sesgo": "centro_der",
    },
    {
        "slug": "el-plural",
        "nombre": "El Plural",
        "rss_url": "https://www.elplural.com/feed/",
        "web_url": "https://www.elplural.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#d90429",
        "sesgo": "izquierda",
    },
    {
        "slug": "la-vanguardia",
        "nombre": "La Vanguardia",
        "rss_url": "https://www.lavanguardia.com/rss/home.xml",
        "web_url": "https://www.lavanguardia.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#002b49",
        "sesgo": "centro",
    },

    # === economía y finanzas ===
    {
        "slug": "expansion",
        "nombre": "Expansión",
        "rss_url": "https://e00-expansion.uecdn.es/rss/portada.xml",
        "web_url": "https://www.expansion.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#005291",
        "sesgo": "centro_der",
    },
    {
        "slug": "cinco-dias",
        "nombre": "Cinco Días",
        "rss_url": "https://cincodias.elpais.com/rss/cincodias/portada.xml",
        "web_url": "https://cincodias.elpais.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#004080",
        "sesgo": "centro",
    },

    # === deportes ===
    {
        "slug": "marca",
        "nombre": "Marca",
        "rss_url": "https://e00-marca.uecdn.es/rss/portada.xml",
        "web_url": "https://www.marca.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#cf0a2c",
        "sesgo": "desconocido",
    },
    {
        "slug": "mundo-deportivo",
        "nombre": "Mundo Deportivo",
        "rss_url": "https://www.mundodeportivo.com/rss/home.xml",
        "web_url": "https://www.mundodeportivo.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#d91f26",
        "sesgo": "desconocido",
    },

    # === regional / autonómico ===
    # Andalucía
    {
        "slug": "diario-de-sevilla",
        "nombre": "Diario de Sevilla",
        "rss_url": "https://www.diariodesevilla.es/rss/",
        "web_url": "https://www.diariodesevilla.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#0072ce",
        "sesgo": "centro",
    },
    {
        "slug": "diario-de-cadiz",
        "nombre": "Diario de Cádiz",
        "rss_url": "https://www.diariodecadiz.es/rss/",
        "web_url": "https://www.diariodecadiz.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#004b87",
        "sesgo": "centro",
    },
    {
        "slug": "malaga-hoy",
        "nombre": "Málaga Hoy",
        "rss_url": "https://www.malagahoy.es/rss/",
        "web_url": "https://www.malagahoy.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#008080",
        "sesgo": "centro",
    },
    {
        "slug": "diario-sur",
        "nombre": "Diario Sur (Andalucía)",
        "rss_url": "https://www.diariosur.es/rss/2.0/portada/",
        "web_url": "https://www.diariosur.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#006699",
        "sesgo": "centro",
    },
    {
        "slug": "ideal-granada",
        "nombre": "Ideal (Granada)",
        "rss_url": "https://www.ideal.es/rss/2.0/portada/",
        "web_url": "https://www.ideal.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#d32f2f",
        "sesgo": "centro",
    },
    # País Vasco / Euskadi
    {
        "slug": "el-correo",
        "nombre": "El Correo (País Vasco)",
        "rss_url": "https://www.elcorreo.com/rss/2.0/portada/",
        "web_url": "https://www.elcorreo.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#b80000",
        "sesgo": "centro",
    },
    {
        "slug": "diario-vasco",
        "nombre": "El Diario Vasco",
        "rss_url": "https://www.diariovasco.com/rss/2.0/portada/",
        "web_url": "https://www.diariovasco.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#003366",
        "sesgo": "centro",
    },
    # Cataluña
    {
        "slug": "cronica-global",
        "nombre": "Crónica Global",
        "rss_url": "https://cronicaglobal.elespanol.com/rss/",
        "web_url": "https://cronicaglobal.elespanol.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#cc0000",
        "sesgo": "centro",
    },
    {
        "slug": "metropoli-abierta",
        "nombre": "Metrópoli Abierta (Barcelona)",
        "rss_url": "https://metropoliabierta.elespanol.com/rss/",
        "web_url": "https://metropoliabierta.elespanol.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#007acc",
        "sesgo": "centro",
    },
    {
        "slug": "vilaweb",
        "nombre": "VilaWeb",
        "rss_url": "https://www.vilaweb.cat/feed/",
        "web_url": "https://www.vilaweb.cat",
        "idioma": "ca",
        "pais": "ES",
        "color": "#e65100",
        "sesgo": "izquierda",
    },
    # Comunidad Valenciana
    {
        "slug": "las-provincias",
        "nombre": "Las Provincias (Valencia)",
        "rss_url": "https://www.lasprovincias.es/rss/2.0/portada/",
        "web_url": "https://www.lasprovincias.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#ff9900",
        "sesgo": "centro_der",
    },
    # Galicia
    {
        "slug": "el-progreso",
        "nombre": "El Progreso (Galicia)",
        "rss_url": "https://www.elprogreso.es/rss/",
        "web_url": "https://www.elprogreso.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#005b96",
        "sesgo": "centro",
    },
    # Castilla y León
    {
        "slug": "el-norte-de-castilla",
        "nombre": "El Norte de Castilla",
        "rss_url": "https://www.elnortedecastilla.es/rss/2.0/portada/",
        "web_url": "https://www.elnortedecastilla.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#1a468c",
        "sesgo": "centro",
    },
    # Asturias, Cantabria, Murcia
    {
        "slug": "el-comercio-asturias",
        "nombre": "El Comercio (Asturias)",
        "rss_url": "https://www.elcomercio.es/rss/2.0/portada/",
        "web_url": "https://www.elcomercio.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#8b0000",
        "sesgo": "centro",
    },
    {
        "slug": "el-diario-montanes",
        "nombre": "El Diario Montañés (Cantabria)",
        "rss_url": "https://www.eldiariomontanes.es/rss/2.0/portada/",
        "web_url": "https://www.eldiariomontanes.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#004080",
        "sesgo": "centro",
    },
    {
        "slug": "alerta-cantabria",
        "nombre": "Alerta Cantabria",
        "rss_url": "https://www.eldiarioalerta.com/rss/",
        "web_url": "https://www.eldiarioalerta.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#b22222",
        "sesgo": "centro",
    },
    {
        "slug": "la-verdad-murcia",
        "nombre": "La Verdad de Murcia",
        "rss_url": "https://www.laverdad.es/rss/2.0/portada/",
        "web_url": "https://www.laverdad.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#2e7d32",
        "sesgo": "centro",
    },
    # Extremadura & C. La Mancha & Aragón & Baleares & Canarias
    {
        "slug": "hoy-extremadura",
        "nombre": "Hoy Diario de Extremadura",
        "rss_url": "https://www.hoy.es/rss/2.0/portada/",
        "web_url": "https://www.hoy.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#388e3c",
        "sesgo": "centro",
    },
    {
        "slug": "elperiodico-extremadura",
        "nombre": "El Periódico Extremadura",
        "rss_url": "https://www.elperiodicoextremadura.com/rss/",
        "web_url": "https://www.elperiodicoextremadura.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#d32f2f",
        "sesgo": "centro",
    },
    {
        "slug": "elperiodico-de-aragon",
        "nombre": "El Periódico de Aragón",
        "rss_url": "https://www.elperiodicodearagon.com/rss/",
        "web_url": "https://www.elperiodicodearagon.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#1976d2",
        "sesgo": "centro",
    },
    {
        "slug": "lanza-digital",
        "nombre": "Lanza Digital (C. La Mancha)",
        "rss_url": "https://www.lanzadigital.com/feed/",
        "web_url": "https://www.lanzadigital.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#5d4037",
        "sesgo": "centro",
    },
    {
        "slug": "canarias7",
        "nombre": "Canarias7",
        "rss_url": "https://www.canarias7.es/rss/2.0/portada/",
        "web_url": "https://www.canarias7.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#f57c00",
        "sesgo": "centro",
    },
    {
        "slug": "diariodemallorca",
        "nombre": "Diario de Mallorca",
        "rss_url": "https://www.diariodemallorca.es/rss/",
        "web_url": "https://www.diariodemallorca.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#0288d1",
        "sesgo": "centro",
    },

    # === otros especializados ===
    {
        "slug": "maldita",
        "nombre": "Maldita.es",
        "rss_url": "https://maldita.es/feed/",
        "web_url": "https://maldita.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#ff5a5f",
        "sesgo": "centro_izq",
    },

    # === catalán ===
    {
        "slug": "ara",
        "nombre": "Ara",
        "rss_url": "https://www.ara.cat/rss/",
        "web_url": "https://www.ara.cat",
        "idioma": "ca",
        "pais": "ES",
        "color": "#1a5fb4",
        "sesgo": "centro_izq",
    },
    {
        "slug": "naciodigital",
        "nombre": "Nació Digital",
        "rss_url": "https://www.naciodigital.cat/rss",
        "web_url": "https://www.naciodigital.cat",
        "idioma": "ca",
        "pais": "ES",
        "color": "#f7b500",
        "sesgo": "centro_izq",
    },

    # === Grupo Prensa Ibérica ===
    {
        "slug": "faro-de-vigo",
        "nombre": "Faro de Vigo",
        "rss_url": "https://www.farodevigo.es/rss/2.0/portada/",
        "web_url": "https://www.farodevigo.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#003b6e",
        "sesgo": "centro",
    },
    {
        "slug": "sport",
        "nombre": "Sport",
        "rss_url": "https://www.sport.es/rss/sport-portada.xml",
        "web_url": "https://www.sport.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#e4002b",
        "sesgo": "desconocido",
    },
    {
        "slug": "levante-emv",
        "nombre": "Levante-EMV",
        "rss_url": "https://www.levante-emv.com/rss/2.0/portada/",
        "web_url": "https://www.levante-emv.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#005f9e",
        "sesgo": "centro",
    },
    {
        "slug": "diario-informacion-alicante",
        "nombre": "Diario Información (Alicante)",
        "rss_url": "https://www.diarioinformacion.com/rss/2.0/portada/",
        "web_url": "https://www.diarioinformacion.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#e74c3c",
        "sesgo": "centro",
    },
    {
        "slug": "la-nueva-espana",
        "nombre": "La Nueva España",
        "rss_url": "https://www.lne.es/rss/2.0/portada/",
        "web_url": "https://www.lne.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#1c4e80",
        "sesgo": "centro",
    },
    {
        "slug": "la-opinion-de-murcia",
        "nombre": "La Opinión de Murcia",
        "rss_url": "https://www.laopiniondemurcia.es/rss/2.0/portada/",
        "web_url": "https://www.laopiniondemurcia.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#c0392b",
        "sesgo": "centro",
    },
    {
        "slug": "la-voz-de-galicia",
        "nombre": "La Voz de Galicia",
        "rss_url": "https://www.lavozdegalicia.es/rss/portada/",
        "web_url": "https://www.lavozdegalicia.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#004a8c",
        "sesgo": "centro",
    },

    # === Grupo Henneo ===
    {
        "slug": "la-informacion",
        "nombre": "La Información",
        "rss_url": "https://www.lainformacion.com/rss/portada.xml",
        "web_url": "https://www.lainformacion.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#2c3e50",
        "sesgo": "centro",
    },

    # === Grupo Joly (completo) ===
    {
        "slug": "el-dia-de-cordoba",
        "nombre": "El Día de Córdoba",
        "rss_url": "https://www.eldiadecordoba.es/rss/",
        "web_url": "https://www.eldiadecordoba.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#006633",
        "sesgo": "centro",
    },
    {
        "slug": "huelva-informacion",
        "nombre": "Huelva Información",
        "rss_url": "https://www.huelvainformacion.es/rss/",
        "web_url": "https://www.huelvainformacion.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#8e44ad",
        "sesgo": "centro",
    },
    {
        "slug": "granada-hoy",
        "nombre": "Granada Hoy",
        "rss_url": "https://www.granadahoy.com/rss/",
        "web_url": "https://www.granadahoy.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#e67e22",
        "sesgo": "centro",
    },
    {
        "slug": "europa-sur",
        "nombre": "Europa Sur (Campo de Gibraltar)",
        "rss_url": "https://www.europasur.es/rss/",
        "web_url": "https://www.europasur.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#16a085",
        "sesgo": "centro",
    },
    {
        "slug": "almeria-hoy",
        "nombre": "Almería Hoy",
        "rss_url": "https://www.almeriahoy.com/rss/",
        "web_url": "https://www.almeriahoy.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#f39c12",
        "sesgo": "centro",
    },

    # === Radio nacional ===
    {
        "slug": "cadena-ser",
        "nombre": "Cadena SER",
        "rss_url": "https://cadenaser.com/api/es/portada/rss/",
        "web_url": "https://cadenaser.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#d50000",
        "sesgo": "centro_izq",
    },
    {
        "slug": "onda-cero",
        "nombre": "Onda Cero",
        "rss_url": "https://www.ondacero.es/rss/noticias.xml",
        "web_url": "https://www.ondacero.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#00529b",
        "sesgo": "centro",
    },
    {
        "slug": "rne-noticias",
        "nombre": "RNE / Radio Nacional",
        "rss_url": "https://www.rtve.es/api/radio/programas/rne-noticias.rss",
        "web_url": "https://www.rtve.es/radio/radio-nacional/",
        "idioma": "es",
        "pais": "ES",
        "color": "#007bff",
        "sesgo": "centro",
    },

    # === TV nacional ===
    {
        "slug": "antena3-noticias",
        "nombre": "Antena 3 Noticias",
        "rss_url": "https://www.antena3.com/rss/temas/noticias/",
        "web_url": "https://www.antena3.com/noticias/",
        "idioma": "es",
        "pais": "ES",
        "color": "#ff6600",
        "sesgo": "centro_der",
    },
    {
        "slug": "lasexta-noticias",
        "nombre": "laSexta Noticias",
        "rss_url": "https://www.lasexta.com/rss/temas/noticias/",
        "web_url": "https://www.lasexta.com/noticias/",
        "idioma": "es",
        "pais": "ES",
        "color": "#5cb85c",
        "sesgo": "centro_izq",
    },
    {
        "slug": "telecinco-noticias",
        "nombre": "Telecinco Noticias",
        "rss_url": "https://www.telecinco.es/rss/temas/noticias/",
        "web_url": "https://www.telecinco.es/noticias/",
        "idioma": "es",
        "pais": "ES",
        "color": "#e74c3c",
        "sesgo": "centro",
    },
    {
        "slug": "telemadrid",
        "nombre": "TeleMadrid",
        "rss_url": "https://www.telemadrid.es/rss/",
        "web_url": "https://www.telemadrid.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#e41e20",
        "sesgo": "centro_der",
    },

    # === Prensa económica / financiera adicional ===
    {
        "slug": "negocios-tv",
        "nombre": "Negocios TV",
        "rss_url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCwd8Byi93KbnsYmCcKLExvQ",
        "web_url": "https://www.youtube.com/@NegociosTV",
        "idioma": "es",
        "pais": "ES",
        "color": "#0f3b7d",
        "sesgo": "centro",
    },
    {
        "slug": "el-economista",
        "nombre": "El Economista",
        "rss_url": "https://www.eleconomista.es/rss/rss-ultima-hora.php",
        "web_url": "https://www.eleconomista.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#1abc9c",
        "sesgo": "centro_der",
    },
    {
        "slug": "intereconomia",
        "nombre": "Intereconomía",
        "rss_url": "https://intereconomia.com/feed/",
        "web_url": "https://intereconomia.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#f39c12",
        "sesgo": "derecha",
    },

    # === Prensa nacional adicional ===
    {
        "slug": "la-razon",
        "nombre": "La Razón",
        "rss_url": "https://www.larazon.es/rss.xml",
        "web_url": "https://www.larazon.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#8e44ad",
        "sesgo": "derecha",
    },
    {
        "slug": "publico",
        "nombre": "Público",
        "rss_url": "https://www.publico.es/rss.xml",
        "web_url": "https://www.publico.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#c0392b",
        "sesgo": "izquierda",
    },
    {
        "slug": "ctxt",
        "nombre": "CTXT (Contexto y Acción)",
        "rss_url": "https://ctxt.es/rss",
        "web_url": "https://ctxt.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#2c3e50",
        "sesgo": "izquierda",
    },
    {
        "slug": "vozpopuli",
        "nombre": "Vozpópuli",
        "rss_url": "https://vozpopuli.com/feed/",
        "web_url": "https://vozpopuli.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#e74c3c",
        "sesgo": "derecha",
    },
    {
        "slug": "el-debate",
        "nombre": "El Debate",
        "rss_url": "https://www.eldebate.com/rss/",
        "web_url": "https://www.eldebate.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#003366",
        "sesgo": "derecha",
    },
    {
        "slug": "as-deportes",
        "nombre": "AS",
        "rss_url": "https://as.com/rss/tags/ultimas_noticias.xml",
        "web_url": "https://as.com",
        "idioma": "es",
        "pais": "ES",
        "color": "#d32f2f",
        "sesgo": "desconocido",
    },
    {
        "slug": "diario-navarra",
        "nombre": "Diario de Navarra",
        "rss_url": "https://www.diariodenavarra.es/rss/portada.xml",
        "web_url": "https://www.diariodenavarra.es",
        "idioma": "es",
        "pais": "ES",
        "color": "#c0392b",
        "sesgo": "centro",
    },
    {
        "slug": "naiz",
        "nombre": "Naiz (Euskal Herria)",
        "rss_url": "https://www.naiz.eus/eu/actualidad/noticia.rss",
        "web_url": "https://www.naiz.eus",
        "idioma": "eu",
        "pais": "ES",
        "color": "#27ae60",
        "sesgo": "izquierda",
    },
]
